version: '3'

services:
  db:
    image: mongo
    ports:
      - "27017:27017"

  rabbitmq:
    image: rabbitmq

  speid:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/speid
    links:
      - db
      - rabbitmq
    depends_on:
      - db
      - rabbitmq
    env_file:
      - .env
